blueprint:
  name: Sensor Light
  description: "# SENSOR LIGHT\nVersion: 2.0\n\nThe most common automation used for
    a sensor light. The good thing is, with this automation you can turn ON as many
    lights as you like by selecting an Area, a Device, an Entity or just any combination
    you like using just one sensor to do it. BE CAREFUL when selecting an Area or
    a Device as it will turn On and OFF everything attached, lights, switches, etc.\n\nLet
    us know what you think of this blueprint and for community support including updates:
    [Click Here](https://community.home-assistant.io/t/sensor-light/481048)\n\nThe
    Automation Process:\n - In this example we will use a Motion sensor as the trigger
    but you can use one or multiple [Binary Sensors](https://www.home-assistant.io/integrations/binary_sensor/)
    as the trigger/s.\n - Triggered on a motion sensor and turns the lights ON. \n
    - When no motion is detected a time delay is activated and turns the lights OFF
    Automatically.\n - The lights will stay ON if the motion sensor detects motion
    before the time delay turns the lights OFF. It will then reset the time delay
    after last motion is detected.\n - You have the option to select scenes. This
    allows you to turn ON a scene when motion is detected and turn OFF a scene when
    the time delay has ended.\n - You have the option to use the \"Trigger Sensor
    By-pass\". This allows you to add a switch to manually By-pass the trigger sensor
    so you can use the lights as normal by turning them ON and OFF manually.\n - You
    have the option to use the \"Sun Elevation\". This is used for adding a condition
    to only work when it is dark by setting the suns position to the horizon.\n -
    You have the option to set an Ambient Light Sensor and set the LUX value. This
    is used for adding a condition to only work when it is dark or below the Ambient
    Light LUX Value.\n - You have the option to set a start time and an end time.
    This will only allow it to run between the time periods.\n \n Note: If you turn
    the light on manually and the motion sensor detects motion the light will turn
    off automatically. It is recommended to use the \"Trigger Sensor By-pass\" option
    if you would like to keep the lights ON or OFF for extended time periods.\n \n
    Need help? See our FAQ: [Click Here](https://community.home-assistant.io/t/sensor-light-motion-sensor-sun-elevation-lux-value-scenes-time/481048/6)\n"
  domain: automation
  input:
    motion_trigger:
      name: Trigger Sensor - Binary Sensors
      description: The Sensor/s that turns the lights ON and OFF. The trigger can
        be any [Binary Sensors](https://www.home-assistant.io/integrations/binary_sensor/)
        you like.
      selector:
        entity:
          domain: binary_sensor
          multiple: true
    light_switch:
      name: Lights - Switches - Scenes
      description: The lights that get turned on by the trigger sensor/s. You can
        also add switches and scenes. If adding a scene please read "Scenes To Turn
        OFF" below.
      selector:
        target:
          entity:
            domain:
            - light
            - switch
            - scene
    end_scenes:
      name: Scenes To Turn OFF
      description: If you have selected a scene to be turned ON above and you would
        like it to be turned OFF after the time delay, you must create another identical
        scene with everything OFF and select it here.
      default: []
      selector:
        entity:
          multiple: true
          domain:
          - scene
    time_delay:
      name: Time Delay
      description: The delay time to leave the lights on after the last trigger from
        ON to OFF state is detected.
      default: 5
      selector:
        number:
          min: 0.0
          max: 30.0
          step: 0.5
          unit_of_measurement: minutes
          mode: slider
    include_bypass:
      name: Use The Trigger Sensor By-pass Option (Optional)
      description: Select enable or disable.
      default: none
      selector:
        select:
          options:
          - label: Enable the By-pass option
            value: bypass_enabled
          - label: Disable the By-pass option
            value: bypass_disabled
          multiple: false
          custom_value: false
    motion_bypass:
      name: Trigger Sensor By-pass
      description: Select a switch that will By-pass the trigger sensor and make your
        lights function as normal. The entity cannot be included in the "Lights -
        Switches - Scenes" selection. If you would like to clear this selection type
        the word "none" in the field, click off it and a save option pops up, then
        click save.
      default: none
      selector:
        entity: {}
    include_sun:
      name: Use The Sun Option (Optional)
      description: Select enable or disable.
      default: none
      selector:
        select:
          options:
          - label: Enable the sun option
            value: sun_enabled
          - label: Disable the sun option
            value: sun_disabled
          multiple: false
          custom_value: false
    sun_elevation:
      name: Sun Elevation
      description: This is the angle between the sun and the horizon. Negative values
        mean the sun is BELOW the horizon. Guide is -1.5 (dusk) and -4.0 (dawn).
      default: -1.5
      selector:
        number:
          min: -10.0
          max: 5.0
          step: 0.5
          unit_of_measurement: degrees
          mode: slider
    include_ambient:
      name: Use The Ambient Option (Optional)
      description: Select enable or disable.
      default: none
      selector:
        select:
          options:
          - label: Enable the ambient option
            value: ambient_enabled
          - label: Disable the ambient option
            value: ambient_disabled
          multiple: false
          custom_value: false
    ambient_light_sensor:
      name: Ambient Light Sensor
      description: This is used for adding a condition to only work when it is dark
        or below the Ambient Light LUX Value. If you have selected an entity and you
        would like to clear this selection see our [FAQ](https://community.home-assistant.io/t/sensor-light-motion-sensor-sun-elevation-lux-value-scenes-time/481048/6)
      default: []
      selector:
        entity:
          domain: sensor
          device_class: illuminance
          multiple: false
    ambient_light_options:
      name: Ambient Light Sensor - Site Conditions
      description: In some cases when your lights turn ON your ambient light sensor
        is affected increasing its LUX value. This can cause the lights to go OFF
        prematurely. Please select an option that best suits your installation.
      default: none
      selector:
        select:
          options:
          - label: YES - My Ambient Light Sensor is affected by the Lights
            value: ambient_light_option_enabled
          - label: NO - My Ambient Light Sensor is not affected by the Lights
            value: ambient_light_option_disabled
          multiple: false
          custom_value: false
    ambient_light_value:
      name: Ambient Light LUX Value
      description: Set the Ambient Light Value if you have selected Ambient Light
        Sensor. Guide is 20 lux (dusk) and 80 lux (dawn).
      default: 20
      selector:
        number:
          min: 0.0
          max: 500.0
          step: 10.0
          unit_of_measurement: LUX
          mode: slider
    include_time:
      name: Use The Time Option (Optional)
      description: Use the "Start Time" and the "End Time" values to only run between
        the time periods.
      default: none
      selector:
        select:
          options:
          - label: Enable the time option
            value: time_enabled
          - label: Disable the time option
            value: time_disabled
          multiple: false
          custom_value: false
    after_time:
      name: Start Time
      description: Set the start time.
      default: 00:00:00
      selector:
        time: {}
    before_time:
      name: End Time
      description: Set the end time.
      default: 00:00:00
      selector:
        time: {}
  source_url: https://gist.github.com/Blackshome/6edfec0ff6a25c5da0d07b88dc908238
mode: restart
max_exceeded: silent
variables:
  motion_trigger: !input motion_trigger
  light_switch: !input light_switch
  end_scenes: !input end_scenes
  time_delay: !input time_delay
  include_bypass: !input include_bypass
  motion_bypass: !input motion_bypass
  include_sun: !input include_sun
  sun_elevation: !input sun_elevation
  include_ambient: !input include_ambient
  ambient_light_sensor: !input ambient_light_sensor
  ambient_light_options: !input ambient_light_options
  ambient_light_value: !input ambient_light_value
  include_time: !input include_time
  after_time: !input after_time
  before_time: !input before_time
trigger:
- platform: state
  id: t1
  entity_id: !input motion_trigger
  from: 'off'
  to: 'on'
- platform: numeric_state
  id: t2
  entity_id: sun.sun
  attribute: elevation
  below: !input sun_elevation
- platform: numeric_state
  id: t3
  entity_id: !input ambient_light_sensor
  below: !input ambient_light_value
- platform: time
  id: t4
  at: !input after_time
condition:
- condition: or
  conditions:
  - condition: and
    conditions:
    - condition: state
      entity_id: !input motion_trigger
      match: any
      state: 'on'
  - condition: and
    conditions:
    - condition: state
      entity_id: !input motion_trigger
      state: 'on'
    - condition: trigger
      id: t2
  - condition: and
    conditions:
    - condition: state
      entity_id: !input motion_trigger
      state: 'on'
    - condition: trigger
      id: t3
  - condition: and
    conditions:
    - condition: state
      entity_id: !input motion_trigger
      state: 'on'
    - condition: trigger
      id: t4
- condition: or
  conditions:
  - '{{ include_bypass == ''none'' }}'
  - '{{ motion_bypass == ''none'' }}'
  - '{{ include_bypass == ''bypass_disabled'' }}'
  - '{{ (include_bypass == ''bypass_enabled'') and (states[motion_bypass].state ==
    ''off'') }}'
- condition: or
  conditions:
  - '{{ include_sun == ''none'' }}'
  - '{{ include_sun == ''sun_disabled'' }}'
  - '{{ (include_sun == ''sun_enabled'') and (state_attr(''sun.sun'',''elevation'')
    <= sun_elevation | float(90)) }}'
- condition: or
  conditions:
  - '{{ include_ambient == ''none'' }}'
  - '{{ include_ambient == ''ambient_disabled'' }}'
  - '{{ ambient_light_sensor == ''none'' }}'
  - '{{ ambient_light_value == ''none'' }}'
  - '{{ (include_ambient == ''ambient_enabled'') and (states[ambient_light_sensor].state
    | int < ambient_light_value | int) }}'
  - '{{ (ambient_light_options == ''ambient_light_option_enabled'') and (expand(light_switch.entity_id)
    | selectattr(''state'', ''=='', ''on'') | list | count > 0) }}'
- condition: or
  conditions:
  - '{{ include_time == ''none'' }}'
  - '{{ include_time == ''time_disabled'' }}'
  - condition: and
    conditions:
    - condition: time
      after: !input after_time
      before: !input before_time
    - '{{ include_time == ''time_enabled'' }}'
action:
- alias: Turn on the light
  service: homeassistant.turn_on
  target: !input light_switch
- alias: Wait until motion sensor is off
  wait_for_trigger:
    platform: state
    entity_id: !input motion_trigger
    from: 'on'
    to: 'off'
- alias: Wait the number of minutes that has been set
  delay:
    minutes: !input time_delay
- alias: Turn off the lights
  service: homeassistant.turn_off
  target: !input light_switch
- alias: Turn off the scenes
  service: scene.turn_on
  entity_id: !input end_scenes
